# Generated by Django 5.1.1 on 2025-04-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(),
        ),
    ]
